version: '3.8'

services:
  creditrisk-app:
    build: .
    container_name: creditrisk-ifrs9-studio
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports

  creditrisk-api:
    build: .
    container_name: creditrisk-ifrs9-api
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
